env:
  global:
    - NODE_ENV=test
    - TEST_DATABASE_URL=postgres://postgres@localhost:5432/travis_ci_test
    - APP_URL_FRONTEND=http://localhost:3000/api
language: node_js
node_js:
  - 'stable'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - yarn add sequelize-cli
cache:
  directories:
    - "node_modules"
script:
    - yarn test:reset
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"

